<template>
  <!-- Content-->
  <div>
    <div class="lg:p-12 max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-">
      <form
        class="lg:p-10 p-6 space-y-3 relative bg-white shadow-xl rounded-md"
        @submit.prevent="login"
      >
        <h1 class="lg:text-2xl text-xl font-semibold mb-6">Login</h1>
        <div>
          <label class="mb-0" for="email"> Email Address </label>
          <input
            id="email"
            v-model="form.email"
            type="email"
            placeholder="Info@example.com"
            class="
              h-12
              mt-2
              px-3
              rounded-md
              w-full
              bg-gray-100
              border-transparent
              focus:border-gray-500
              focus:outline-none
              focus:ring-4
              focus:ring-blue-500
              focus:ring-opacity-50
            "
          />
        </div>
        <div>
          <label class="mb-0" for="password"> Password </label>
          <input
            id="password"
            v-model="form.password"
            type="password"
            placeholder="******"
            class="
              h-12
              mt-2
              px-3
              rounded-md
              w-full
              bg-gray-100
              border-transparent
              focus:border-gray-500
              focus:outline-none
              focus:ring-4
              focus:ring-blue-500
              focus:ring-opacity-50
            "
          />
        </div>

        <div>
          <button
            type="submit"
            class="
              button-login
              bg-blue-600
              font-semibold
              p-2.5
              mt-5
              rounded-md
              text-center text-white
              w-full
              flex
              items-center
              justify-content-center
              disabled:opacity-50 disabled:cursor-wait
            "
            :disabled="loading"
          >
            <svg
              v-if="loading"
              class="w-8 h-8"
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              viewBox="0 0 100 100"
              preserveAspectRatio="xMidYMid"
            >
              <circle
                cx="50"
                cy="50"
                fill="none"
                stroke="#d8ebf9"
                stroke-width="10"
                r="35"
                stroke-dasharray="164.93361431346415 56.97787143782138"
              >
                <animateTransform
                  attributeName="transform"
                  type="rotate"
                  repeatCount="indefinite"
                  dur="1s"
                  values="0 50 50;360 50 50"
                  keyTimes="0;1"
                ></animateTransform>
              </circle>
              <!-- [ldio] generated by https://loading.io/ -->
            </svg>
            Login
          </button>
        </div>

        <div class="uk-heading-line uk-text-center py-5">
          <span> Belum punya akun ? </span>
        </div>

        <nuxt-link
          :to="{ name: 'account-register' }"
          class="
            relative
            inline-block
            text-center
            w-full
            p-2.5
            mt-2
            font-semibold
            border border-indigo-500
            hover:text-indigo-500
            rounded-lg
            cursor-pointer
          "
        >
          Register
        </nuxt-link>
      </form>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Login',
  layout: 'full',
  auth: 'guest',
  data() {
    return {
      loading: false,
      form: {
        email: 'icoferaldo@gmail.com',
        password: 'password',
      },
    }
  },
  methods: {
    async login() {
      try {
        this.loading = true
        await this.$auth.loginWith('laravelJWT', {
          auth: {
            username: this.form.email,
            password: this.form.password,
          },
        })
      } catch (error) {
        alert('Login Gagal : Email atau Password Salah')
      } finally {
        this.loading = false
      }
    },
  },
}
</script>

<style lang="scss" scoped></style>
