<template>
  <!-- Content-->
  <div
    class="
      min-h-screen
      bg-purple-400
      flex
      justify-center
      items-center
      overflow-hidden
      relative
    "
  >
    <div
      class="
        absolute
        w-48
        h-48
        rounded-xl
        bg-purple-300
        -top-5
        -left-16
        z-0
        transform
        rotate-45
        hidden
        md:block
      "
    ></div>
    <div
      class="
        absolute
        w-48
        h-48
        rounded-xl
        bg-purple-300
        -bottom-6
        -right-10
        transform
        rotate-12
        hidden
        md:block
      "
    ></div>
    <div class="py-12 px-12 bg-white rounded-2xl shadow-xl z-20">
      <div>
        <h1 class="text-3xl font-bold text-center mb-4 cursor-pointer">
          Sign In
        </h1>
        <p
          class="
            w-80
            text-center text-sm
            mb-8
            font-semibold
            text-gray-700
            tracking-wide
            cursor-pointer
          "
        >
          Please login to continue exploring around the world
        </p>
      </div>
      <div class="space-y-4">
        <form @submit.prevent="login">
          <div class="mb-3">
            <label class="mb-0" for="email"> Email Address </label>
            <input
              id="email"
              v-model="form.email"
              type="email"
              placeholder="Info@example.com"
              class="
                h-12
                mt-2
                px-3
                rounded-md
                w-full
                bg-gray-100
                border-transparent
                focus:border-gray-500
                focus:outline-none
                focus:ring-4
                focus:ring-purple-500
                focus:ring-opacity-50
              "
            />
          </div>
          <div>
            <label class="mb-0" for="password"> Password </label>
            <input
              id="password"
              v-model="form.password"
              type="password"
              placeholder="******"
              class="
                h-12
                mt-2
                px-3
                rounded-md
                w-full
                bg-gray-100
                border-transparent
                focus:border-gray-500
                focus:outline-none
                focus:ring-4
                focus:ring-purple-500
                focus:ring-opacity-50
              "
            />
          </div>

          <div>
            <button
              type="submit"
              class="
                button-login
                bg-purple-600
                font-semibold
                p-2.5
                mt-5
                rounded-md
                text-center text-white
                w-full
                flex
                items-center
                justify-content-center
                disabled:opacity-50 disabled:cursor-wait
              "
              :disabled="loading"
            >
              <svg
                v-if="loading"
                class="w-6 h-6"
                xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                viewBox="0 0 100 100"
                preserveAspectRatio="xMidYMid"
              >
                <circle
                  cx="50"
                  cy="50"
                  fill="none"
                  stroke="#d8ebf9"
                  stroke-width="10"
                  r="35"
                  stroke-dasharray="164.93361431346415 56.97787143782138"
                >
                  <animateTransform
                    attributeName="transform"
                    type="rotate"
                    repeatCount="indefinite"
                    dur="1s"
                    values="0 50 50;360 50 50"
                    keyTimes="0;1"
                  ></animateTransform>
                </circle>
                <!-- [ldio] generated by https://loading.io/ -->
              </svg>
              Login
            </button>
          </div>

          <div class="uk-heading-line uk-text-center py-5">
            <span> Belum punya akun ? </span>
          </div>

          <nuxt-link
            :to="{ name: 'account-register' }"
            class="
              relative
              inline-block
              text-center
              w-full
              p-2.5
              mt-2
              font-semibold
              border border-indigo-500
              hover:text-indigo-500
              rounded-lg
              cursor-pointer
            "
          >
            Register
          </nuxt-link>
        </form>
      </div>
    </div>
    <div
      class="
        w-40
        h-40
        absolute
        bg-purple-300
        rounded-full
        top-0
        right-12
        hidden
        md:block
      "
    ></div>
    <div
      class="
        w-20
        h-40
        absolute
        bg-purple-300
        rounded-full
        bottom-20
        left-10
        transform
        rotate-45
        hidden
        md:block
      "
    ></div>
  </div>
</template>

<script>
export default {
  name: 'Login',
  layout: 'full',
  auth: 'guest',
  data() {
    return {
      loading: false,
      form: {
        email: 'icoferaldo@gmail.com',
        password: 'password',
      },
    }
  },
  methods: {
    async login() {
      try {
        this.loading = true
        await this.$auth.loginWith('laravelJWT', {
          auth: {
            username: this.form.email,
            password: this.form.password,
          },
        })
      } catch (error) {
        alert('Login Gagal : Email atau Password Salah')
      } finally {
        this.loading = false
      }
    },
  },
}
</script>

<style lang="scss" scoped></style>
