<template>
  <!-- Content-->
  <div>
    <div class="lg:p-12 max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-">
      <form
        class="lg:p-10 p-6 space-y-3 relative bg-white shadow-xl rounded-md"
        @submit.prevent="submit"
      >
        <h1 class="lg:text-2xl text-xl font-semibold mb-6">Register</h1>
        <div>
          <label class="mb-0"> Nama Lengkap </label>
          <input
            v-model="form.name"
            type="text"
            placeholder="Your Name"
            class="bg-gray-100 h-12 mt-2 px-3 rounded-md w-full"
          />
        </div>
        <div>
          <label class="mb-0"> Alamat Email </label>
          <input
            v-model="form.email"
            type="email"
            placeholder="Info@example.com"
            class="bg-gray-100 h-12 mt-2 px-3 rounded-md w-full"
          />
        </div>
        <div>
          <label class="mb-0"> Password </label>
          <input
            v-model="form.password"
            type="password"
            placeholder="******"
            class="bg-gray-100 h-12 mt-2 px-3 rounded-md w-full"
          />
        </div>

        <div>
          <label class="mb-0"> Konfirmasi Password </label>
          <input
            v-model="form.password_confirmation"
            type="password"
            placeholder="******"
            class="bg-gray-100 h-12 mt-2 px-3 rounded-md w-full"
          />
        </div>

        <div class="checkbox">
          <input id="chekcbox1" type="checkbox" checked="" />
          <label for="chekcbox1"
            ><span class="checkbox-icon"></span> I agree to the
            <a
              href="pages-terms.html"
              target="_blank"
              class="uk-text-bold uk-text-small uk-link-reset"
            >
              Terms and Conditions
            </a>
          </label>
        </div>

        <div class="text-center">
          <button
            type="submit"
            class="
              mb-2
              bg-blue-600
              font-semibold
              p-2
              mt-5
              rounded-md
              text-center text-white
              w-full
              flex
              items-center
              justify-content-center
            "
            :class="{ 'opacity-50': loading }"
            :disabled="loading"
          >
            <svg
              v-if="loading"
              class="w-8 h-8"
              xmlns="http://www.w3.org/2000/svg"
              xmlns:xlink="http://www.w3.org/1999/xlink"
              viewBox="0 0 100 100"
              preserveAspectRatio="xMidYMid"
            >
              <circle
                cx="50"
                cy="50"
                fill="none"
                stroke="#d8ebf9"
                stroke-width="10"
                r="35"
                stroke-dasharray="164.93361431346415 56.97787143782138"
              >
                <animateTransform
                  attributeName="transform"
                  type="rotate"
                  repeatCount="indefinite"
                  dur="1s"
                  values="0 50 50;360 50 50"
                  keyTimes="0;1"
                ></animateTransform>
              </circle>
              <!-- [ldio] generated by https://loading.io/ -->
            </svg>
            Get Started
          </button>
          <nuxt-link :to="{ name: 'account-login' }"
            >Saya sudah punya akun</nuxt-link
          >
        </div>
      </form>
    </div>
  </div>
</template>

<script>
export default {
  layout: 'full',
  auth: 'guest',
  data() {
    return {
      loading: false,
      form: {},
    }
  },
  methods: {
    async submit() {
      try {
        this.loading = true
        await this.$axios.post('/auth/register', this.form)

        await this.$auth.loginWith('laravelJWT', {
          auth: {
            username: this.form.email,
            password: this.form.password,
          },
        })
      } catch (error) {
        alert('Gagal Register')
      } finally {
        this.loading = false
      }
    },
  },
}
</script>

<style lang="scss" scoped></style>
