<template>
  <div>
    <!-- course preview details -->
    <CoursePreview :course="course" />

    <!--  course tabs -->
    <div
      class="bg-white border-b z-20 mb-4 overflow-hidden"
      uk-sticky="media: 992 ; offset:70"
    >
      <div class="mcontainer py-0 lg:px-32 flex justify-between items-center">
        <nav class="cd-secondary-nav flex-1">
          <ul class="space-x-3" uk-scrollspy-nav="closest: li; scroll: true">
            <li><a href="#Overview" uk-scroll>Overview</a></li>
            <li><a href="#curriculum" uk-scroll>Curriculum</a></li>
            <li><a href="#faq" uk-scroll>FAQ</a></li>
            <li><a href="#announcement">Announcement</a></li>
            <li><a href="#reviews">Reviews</a></li>
          </ul>
        </nav>

        <div class="flex space-x-3 lg:-mr-5">
          <!-- <a
            href="#"
            class="
              flex
              items-center
              justify-center
              h-10
              px-6
              rounded-md
              bg-gray-100
            "
          >
            Add to Wishlist
          </a> -->
          <template v-if="!isEnrolled">
            <button
              v-if="course.price < 1"
              type="button"
              class="
                flex
                items-center
                justify-center
                h-10
                px-6
                rounded-md
                bg-purple-600
                hover:bg-purple-700
                text-white
                hover:text-white
                disabled:opacity-50
              "
              :disabled="orderLoading"
              @click="order"
            >
              <svg
                v-if="orderLoading"
                class="w-8 h-8"
                xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                viewBox="0 0 100 100"
                preserveAspectRatio="xMidYMid"
              >
                <circle
                  cx="50"
                  cy="50"
                  fill="none"
                  stroke="#d8ebf9"
                  stroke-width="10"
                  r="35"
                  stroke-dasharray="164.93361431346415 56.97787143782138"
                >
                  <animateTransform
                    attributeName="transform"
                    type="rotate"
                    repeatCount="indefinite"
                    dur="1s"
                    values="0 50 50;360 50 50"
                    keyTimes="0;1"
                  ></animateTransform>
                </circle>
                <!-- [ldio] generated by https://loading.io/ -->
              </svg>
              Bergabung Sekarang
            </button>

            <nuxt-link
              v-if="course.price > 0"
              disabled
              class="
                flex
                items-center
                justify-center
                h-10
                px-6
                rounded-md
                bg-purple-600
                hover:bg-purple-700
                text-white
                hover:text-white
                disabled:opacity-50
              "
              :to="{ name: 'orders-slug', params: { slug: course.slug } }"
            >
              Beli Sekarang
            </nuxt-link>
          </template>
          <template v-else>
            <nuxt-link
              v-if="course.price > 0"
              disabled
              class="
                flex
                items-center
                justify-center
                h-10
                px-6
                rounded-md
                bg-purple-600
                hover:bg-purple-700
                text-white
                hover:text-white
                disabled:opacity-50
              "
              :to="{ name: 'learn-slug', params: { slug: course.slug } }"
            >
              Lanjutkan Belajar
            </nuxt-link>
          </template>
        </div>
      </div>
    </div>

    <div class="container p-0">
      <div class="space-y-5 lg:w-8/12 mx-auto">
        <!-- course description -->
        <div id="Overview" class="tube-card p-5 lg:p-8">
          <div class="space-y-6">
            <div>
              <h3 class="text-xl font-semibold mb-3">Description</h3>
              <!-- eslint-disable-next-line vue/no-v-html -->
              <div v-html="course.descriptions"></div>
            </div>
          </div>
        </div>

        <!-- course Curriculum -->
        <div id="curriculum">
          <CourseCurriculum :course="course" />
        </div>

        <!-- course Faq -->
        <!-- <div id="faq" class="tube-card p-5 lg:p-8">
          <h3 class="text-xl font-semibold mb-3 lg:mb-5">Course Faq</h3>

          <ul uk-accordion="multiple: true" class="divide-y space-y-3">
            <li class="bg-gray-100 px-4 py-3 rounded-md uk-open">
              <a class="uk-accordion-title font-semibold text-base" href="#">
                Html Introduction
              </a>
              <div class="uk-accordion-content mt-3">
                <p>
                  The primary goal of this quick start guide is to introduce you
                  to Unreal Engine 4`s (UE4) development environment. By the end
                  of this guide, you`ll know how to set up and develop C++
                  Projects in UE4. This guide shows you how to create a new
                  Unreal Engine project, add a new C++ class to it, compile the
                  project, and add an instance of a new class to your level. By
                  the time you reach the end of this guide, you`ll be able to
                  see your programmed Actor floating above a table in the level.
                </p>
              </div>
            </li>
            <li class="bg-gray-100 px-4 py-3 rounded-md">
              <a class="uk-accordion-title font-semibold text-base" href="#">
                Your First webpage</a
              >
              <div class="uk-accordion-content mt-3">
                <p>
                  The primary goal of this quick start guide is to introduce you
                  to Unreal Engine 4`s (UE4) development environment. By the end
                  of this guide, you`ll know how to set up and develop C++
                  Projects in UE4. This guide shows you how to create a new
                  Unreal Engine project, add a new C++ class to it, compile the
                  project, and add an instance of a new class to your level. By
                  the time you reach the end of this guide, you`ll be able to
                  see your programmed Actor floating above a table in the level.
                </p>
              </div>
            </li>
            <li class="bg-gray-100 px-4 py-3 rounded-md">
              <a class="uk-accordion-title font-semibold text-base" href="#">
                Some Special Tags
              </a>
              <div class="uk-accordion-content mt-3">
                <p>
                  The primary goal of this quick start guide is to introduce you
                  to Unreal Engine 4`s (UE4) development environment. By the end
                  of this guide, you`ll know how to set up and develop C++
                  Projects in UE4. This guide shows you how to create a new
                  Unreal Engine project, add a new C++ class to it, compile the
                  project, and add an instance of a new class to your level. By
                  the time you reach the end of this guide, you`ll be able to
                  see your programmed Actor floating above a table in the level.
                </p>
              </div>
            </li>
            <li class="bg-gray-100 px-4 py-3 rounded-md">
              <a class="uk-accordion-title font-semibold text-base" href="#">
                Html Introduction
              </a>
              <div class="uk-accordion-content mt-3">
                <p>
                  The primary goal of this quick start guide is to introduce you
                  to Unreal Engine 4`s (UE4) development environment. By the end
                  of this guide, you`ll know how to set up and develop C++
                  Projects in UE4. This guide shows you how to create a new
                  Unreal Engine project, add a new C++ class to it, compile the
                  project, and add an instance of a new class to your level. By
                  the time you reach the end of this guide, you`ll be able to
                  see your programmed Actor floating above a table in the level.
                </p>
              </div>
            </li>
          </ul>
        </div> -->

        <!-- course Announcement -->
        <!-- <div id="announcement" class="tube-card p-5 lg:p-8">
          <h3 class="text-xl font-semibold lg:mb-5">Announcement</h3>

          <div class="flex items-center gap-x-4 mb-5">
            <img
              src="images/avatars/avatar-4.jpg"
              alt=""
              class="rounded-full shadow w-12 h-12"
            />
            <div>
              <h4 class="-mb-1 text-base">Stella Johnson</h4>
              <span class="text-sm">
                Instructor <span class="text-gray-500"> 1 year ago </span>
              </span>
            </div>
          </div>

          <h4 class="leading-8 text-xl">
            Nam liber tempor cum soluta nobis eleifend option congue imperdiet
            doming id quod mazim placerat facer possim assum.
          </h4>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
            nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat
            volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation
            ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo
            consequat. Nam liber tempor cum soluta nobis eleifend option congue
            nihil imperdiet doming id quod mazim placerat facer possim assum.
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
            nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat
            volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation
            ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo
            consequat.
          </p>
        </div> -->

        <!-- course Reviews -->
        <!-- <div id="reviews" class="tube-card p-5 lg:p-8">
          <h3 class="text-xl font-semibold lg:mb-5">Reviews (4610)</h3>

          <div id="reviews" class="flex space-x-5 mb-8">
            <div class="lg:w-1/4 w-full">
              <div
                class="
                  bg-purple-100
                  p-6
                  rounded-md
                  border border-purple-200
                  text-center
                  shadow-xs
                "
              >
                <h1 class="leading-none text-6xl">4.8</h1>
                <div class="flex justify-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-gray-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                </div>
                <h5 class="text-lg mb-0 mt-2 text-purple-800">Course Rating</h5>
              </div>
            </div>
            <div class="w-2/4 hidden lg:flex flex-col justify-center">
              <div class="space-y-5">
                <div
                  class="w-full h-3 rounded-lg bg-gray-300 shadow-xs relative"
                >
                  <div class="w-11/12 h-3 rounded-lg bg-gray-800"></div>
                </div>
                <div
                  class="w-full h-3 rounded-lg bg-gray-300 shadow-xs relative"
                >
                  <div class="w-4/5 h-3 rounded-lg bg-gray-800"></div>
                </div>
                <div
                  class="w-full h-3 rounded-lg bg-gray-300 shadow-xs relative"
                >
                  <div class="w-3/5 h-3 rounded-lg bg-gray-800"></div>
                </div>
                <div
                  class="w-full h-3 rounded-lg bg-gray-300 shadow-xs relative"
                >
                  <div class="w-3/6 h-3 rounded-lg bg-gray-800"></div>
                </div>
                <div
                  class="w-full h-3 rounded-lg bg-gray-300 shadow-xs relative"
                >
                  <div class="w-1/3 h-3 rounded-lg bg-gray-800"></div>
                </div>
              </div>
            </div>
            <div class="w-1/4 hidden lg:flex flex-col justify-center">
              <div class="space-y-1">
                <div class="flex justify-center items-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <span class="ml-2"> 95 %</span>
                </div>
                <div class="flex justify-center items-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-gray-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <span class="ml-2"> 85 %</span>
                </div>
                <div class="flex justify-center items-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-gray-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <span class="ml-2"> 60 %</span>
                </div>
                <div class="flex justify-center items-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-gray-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <span class="ml-2"> 50 %</span>
                </div>
                <div class="flex justify-center items-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-orange-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="w-5 h-5 text-gray-400"
                  >
                    <path
                      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                    ></path>
                  </svg>
                  <span class="ml-2"> 35 %</span>
                </div>
              </div>
            </div>
          </div>

          <div class="space-y-4 my-5">
            <div class="bg-gray-50 border flex gap-x-4 p-4 relative rounded-md">
              <img
                src="images/avatars/avatar-4.jpg"
                alt=""
                class="rounded-full shadow w-12 h-12"
              />
              <div
                class="
                  flex
                  justify-center
                  items-center
                  absolute
                  right-5
                  top-6
                  space-x-1
                  text-yellow-500
                "
              >
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
              </div>
              <div>
                <h4 class="text-base m-0 font-semibold">Stella Johnson</h4>
                <span class="text-gray-700 text-sm"> 14th, April 2021 </span>
                <p class="mt-3 md:ml-0 -ml-16">
                  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed
                  diam ut laoreet dolore magna aliquam erat volutpat. Ut wisi
                  enim ad minim veniam, quis nostrud exerci tation ullamcorper
                  suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </p>
              </div>
            </div>

            <div class="bg-gray-50 border flex gap-x-4 p-4 relative rounded-md">
              <div
                class="
                  flex
                  justify-center
                  items-center
                  absolute
                  right-5
                  top-6
                  space-x-1
                  text-yellow-500
                "
              >
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star" class="text-gray-300"></ion-icon>
              </div>
              <img
                src="images/avatars/avatar-2.jpg"
                alt=""
                class="rounded-full shadow w-12 h-12"
              />
              <div>
                <h4 class="text-base m-0 font-semibold">Alex Dolgove</h4>
                <span class="text-gray-700 text-sm"> 16th, May 2021 </span>
                <p class="mt-3 md:ml-0 -ml-16">
                  elit, sed diam ut laoreet dolore magna aliquam erat volutpat.
                  Ut wisi enim ad minim ipsum dolor sit amet, consectetuer
                  adipiscing elit, sed diam ut laoreet dolore
                </p>
              </div>
            </div>

            <div
              class="
                bg-gray-50
                border
                flex
                gap-x-4
                p-4
                relative
                rounded-md
                lg:ml-16
              "
            >
              <div
                class="
                  flex
                  justify-center
                  items-center
                  absolute
                  right-5
                  top-6
                  space-x-1
                  text-yellow-500
                "
              >
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star"></ion-icon>
                <ion-icon name="star" class="text-gray-300"></ion-icon>
              </div>
              <img
                src="images/avatars/avatar-3.jpg"
                alt=""
                class="rounded-full shadow w-12 h-12"
              />
              <div>
                <h4 class="text-base m-0 font-semibold">Trap Nation</h4>
                <span class="text-gray-700 text-sm"> 16th, May 2021 </span>
                <p class="mt-3 md:ml-0 -ml-16">
                  elit, sed diam ut laoreet dolore magna aliquam erat volutpat.
                  Ut wisi enim ad minim ipsum dolor sit amet, consectetuer
                  adipiscing elit, sed diam ut laoreet dolore
                </p>
              </div>
            </div>
          </div>

          <div class="flex justify-center mt-9">
            <a
              href="#"
              class="
                bg-gray-50
                border
                hover:bg-gray-100
                px-4
                py-1.5
                rounded-full
                text-sm
              "
              >More Comments ..</a
            >
          </div>
        </div> -->
      </div>
    </div>

    <!-- video demo model -->
    <div id="trailer-modal" uk-modal>
      <div class="uk-modal-dialog shadow-lg rounded-md">
        <button
          class="uk-modal-close-default m-2.5"
          type="button"
          uk-close
        ></button>
        <div class="uk-modal-header rounded-t-md">
          <h4 class="text-lg font-semibold mb-2">Trailer video</h4>
        </div>

        <div class="embed-video">
          <iframe
            :src="course.trailer_url"
            class="w-full"
            uk-video="automute: true"
            frameborder="0"
            allowfullscreen
            uk-responsive
          ></iframe>
        </div>

        <div class="uk-modal-body">
          <h3 class="text-lg font-semibold mb-2">Build Responsive Websites</h3>
          <p>
            Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
            cupidatat non proident, sunt in culpa qui officia deserunt mollit
            anim id est laborum.
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import CourseCurriculum from '@/components/partials/courses/detail/CourseCurriculum.vue'
import CoursePreview from '@/components/partials/courses/detail/CoursePreview.vue'
import { mapState } from 'vuex'

export default {
  components: {
    CourseCurriculum,
    CoursePreview,
  },
  async asyncData({ params, store, $axios }) {
    try {
      let isEnrolled = false
      const result = await store.dispatch('course/loadCourse', {
        slug: params.slug,
      })

      if (result) {
        const checkEnrolled = await $axios.get('/user-courses', {
          params: {
            course_id: store.state.course.course.id,
            user_id: store.state.auth.user.id,
          },
        })

        if (checkEnrolled.data.data.length > 0) {
          isEnrolled = true
        }
      }

      return {
        isEnrolled,
      }
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error(error)
    }
  },
  data() {
    return {
      orderLoading: false,
    }
  },
  computed: {
    ...mapState({
      course: (state) => state.course.course,
    }),
  },
  methods: {
    async order() {
      try {
        this.orderLoading = true
        const response = await this.$axios.post('/orders/enroll', {
          course_id: this.course.id,
        })

        if (response.status === 201) {
          this.$router.push({ name: 'orders-thank-you' })
        }
      } catch (error) {
      } finally {
        this.orderLoading = false
      }
    },
  },
}
</script>

<style lang="scss" scoped></style>
